#!/usr/bin/env python3
"""
experiments/exp_bm3_cwru_leakfree/run_p14_coverage.py

P14 driver: runs the 2 configs (single, dual) generated by
gen_configs_p14_coverage.py sequentially. Idempotent — train_p14_coverage_
leakfree.py already skips any (combo, seed) whose JSON exists, and this
driver additionally skips a whole config if its summary.json already
exists (matches the run_batch*.py pattern used throughout this project).
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
CFG_DIR = Path(__file__).parent / "configs_p14_coverage"
DRIVER = Path(__file__).parent / "train_p14_coverage_leakfree.py"
MANIFEST = Path(__file__).parent / "run_manifest_p14_coverage.json"


def main():
    with open(MANIFEST) as f:
        manifest = json.load(f)

    for row in manifest:
        results_dir = Path(row["results_dir"])
        summary_path = results_dir / "summary.json"
        if summary_path.exists():
            print(f"[SKIP config] {row['family']} — summary.json already exists at {summary_path}")
            continue

        cfg_path = ROOT / row["p14_config"]
        print(f"\n{'#'*70}")
        print(f"# Running {row['family']} ({row['arm']}) -> {results_dir}")
        print(f"{'#'*70}\n")
        cmd = [sys.executable, str(DRIVER), "--config", str(cfg_path)]
        ret = subprocess.run(cmd, cwd=str(ROOT))
        if ret.returncode != 0:
            print(f"[ERROR] {row['family']} failed with exit code {ret.returncode}")
            sys.exit(ret.returncode)

    print("\nAll P14 coverage-sweep configs complete.")


if __name__ == "__main__":
    main()
