#!/usr/bin/env python3
"""
E3 config field audit — loads the four config_lobo_*_leakfree.yaml files and
reconciles their cost-relevant fields against the run matrix declared in
e3_cost_estimate.md (4 folds x 4 arms x 5 seeds = 80 runs).

Read-only: does not import training code, does not touch results/.
Re-run any time with:
    python3 experiments/exp_e3_lobo_leakfree/audit_config_fields.py
"""
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent

# arm -> (config file, expected n_sensors, expected lambda_kin)
EXPECTED = {
    "single_nokin": ("config_lobo_nokin_leakfree.yaml", 1, 0.0),
    "single_kin": ("config_lobo_kin_leakfree.yaml", 1, 0.01),
    "dual_nokin": ("config_lobo_dual_nokin_leakfree.yaml", 2, 0.0),
    "dual_kin": ("config_lobo_dual_kin_leakfree.yaml", 2, 0.01),
}

FIELDS = [
    "selection_mode",
    "save_checkpoint",
    "n_sensors",
    "epochs",
    "seeds",
    "lambda_kin",
    "fs_eff",
    "results_dir",
]

RESULTS_ROOT = "<REPO_ROOT>/results/e3_lobo_leakfree_20260709-1532"
N_FOLDS = 4  # Cond3 LOBO: Bearing3_1/3_3/3_4/3_5, from make_lobo_folds() (not a config field)


def load_cfg(fname):
    with open(HERE / fname) as f:
        return yaml.safe_load(f)


def audit():
    rows = []
    all_pass = True
    for arm, (fname, exp_n_sensors, exp_lambda_kin) in EXPECTED.items():
        cfg = load_cfg(fname)
        checks = {}

        checks["selection_mode"] = (cfg.get("selection_mode") == "fixed_epoch",
                                     cfg.get("selection_mode"))
        checks["save_checkpoint"] = (cfg.get("save_checkpoint") is True,
                                      cfg.get("save_checkpoint"))
        checks["n_sensors"] = (cfg.get("n_sensors") == exp_n_sensors,
                                cfg.get("n_sensors"))
        checks["epochs"] = (cfg.get("epochs") == 50, cfg.get("epochs"))
        seeds = cfg.get("seeds")
        checks["seeds"] = (seeds == [0, 1, 2, 3, 4], seeds)
        checks["lambda_kin"] = (cfg.get("lambda_kin") == exp_lambda_kin,
                                 cfg.get("lambda_kin"))
        checks["fs_eff"] = (cfg.get("fs_eff") == 12800.0, cfg.get("fs_eff"))
        results_dir = cfg.get("results_dir", "")
        checks["results_dir"] = (
            results_dir == f"{RESULTS_ROOT}/{arm}",
            results_dir,
        )

        row_pass = all(v[0] for v in checks.values())
        all_pass = all_pass and row_pass
        rows.append((arm, fname, checks, row_pass))

    return rows, all_pass


def render_markdown(rows, all_pass):
    lines = []
    lines.append("# E3 config field audit (auto-generated, re-runnable)\n")
    lines.append(
        "Generated by `audit_config_fields.py`. Loads the four "
        "`config_lobo_*_leakfree.yaml` files and checks every cost-relevant "
        "field against the 4-fold x 4-arm x 5-seed = 80-run matrix declared "
        "in `e3_cost_estimate.md`.\n"
    )
    header = "| arm | config file | " + " | ".join(FIELDS) + " | row PASS |"
    sep = "|---" * (len(FIELDS) + 3) + "|"
    lines.append(header)
    lines.append(sep)
    for arm, fname, checks, row_pass in rows:
        cells = [arm, f"`{fname}`"]
        for field in FIELDS:
            ok, val = checks[field]
            mark = "OK" if ok else "FAIL"
            cells.append(f"{val} [{mark}]")
        cells.append("PASS" if row_pass else "FAIL")
        lines.append("| " + " | ".join(str(c) for c in cells) + " |")
    lines.append("")

    lines.append("## Cross-check against cost matrix\n")
    n_arms = len(rows)
    n_seeds = 5
    total_runs = N_FOLDS * n_arms * n_seeds
    lines.append(f"- folds (from `make_lobo_folds()`, not a config field): {N_FOLDS}")
    lines.append(f"- arms (= number of distinct config files audited): {n_arms}")
    lines.append(f"- seeds per arm (from `seeds:` field, verified above): {n_seeds}")
    lines.append(
        f"- total runs = {N_FOLDS} folds x {n_arms} arms x {n_seeds} seeds = "
        f"**{total_runs}**, matches `e3_cost_estimate.md` matrix (80) : "
        f"{'PASS' if total_runs == 80 else 'FAIL'}"
    )
    lines.append("")
    lines.append(
        f"## Overall verdict: {'PASS — all 4 configs, all 8 fields reconciled' if all_pass else 'FAIL — see [FAIL] cells above'}\n"
    )
    return "\n".join(lines)


if __name__ == "__main__":
    rows, all_pass = audit()
    md = render_markdown(rows, all_pass)
    print(md)
    sys.exit(0 if all_pass else 1)
